### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-claramiralles#1]
Buen trabajo @claramiralles !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Si utilizas SASS, recuerda instalarlo y grabarlo en el package.json con `--save`
- [x] En el componente del listado hay que recorrer el array de pokemons que le llega por props y pintar una tarjeta por cada uno.
- [x] Recuerda que en JSX utilizamos `{ }` para poder escribir JavaScript dentro. Si quieres añadir un objeto primero necesitas las llaves de JSX para indicar que vas a escribir JS y después las del objeto.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el li fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un ul
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [ ] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by claramiralles** [comment]
Gracias por los comentarios @nasivuela. He corregido todo y ademas he añadido un service para los datos, para que esté más organizado. He seguido el proceso para publicar en Github Pages pero por alguna razón que no logro encontrar no se publica. ¿Alguna idea? Gracias por adelantado!!

**Comment by claramiralles** [comment]
Hola @nasivuela! He añadido también un botón de favoritos!

**Comment by nasivuela** [comment]
Pero que buen trabajo!

Para publicar en GP react, recuerda que tienes que añadir algo al package.json ;)

Cierro issue, pero te dejo otros retos por si te animas:

- Añade una página de detalle para cada Pokemon

- Permite que se seleccionen varios favoritos, para ello hay que:
1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

![](https://media.giphy.com/media/l2SpXyO9TOJCrCbo4/giphy.gif)
